- block:
  - name: template > generate resolv.conf
    template:
      src:  resolv.conf
      dest: /etc/resolv.conf
    when: inventory_hostname != "chroot"      # resolv.conf is locked by arch-chroot

  - name: lineinfile > create /etc/hostname and add {{ hostname }}
    lineinfile:
      path:   /etc/hostname
      line:   "{{ hostname }}"
      create: yes
    register: r_hostname
    when: hostname | length

  - name: shell > update systemd hostname without reboot
    shell: hostnamectl set-hostname {{ hostname }}
    when:
      - r_hostname.changed
      - sysinit == "systemd"
      - ansible_hostname != hostname
      - inventory_hostname != "chroot"

  - name: template > add domains to /etc/hosts
    template:
      src:  hosts
      dest: /etc/hosts
      mode: 0644
    when: inventory_hostname != "chroot"  ## why KO in chroot ?

  - name: lineinfile > set hostname for openrc
    lineinfile:
      path:   /etc/conf.d/hostname
      regexp: "^hostname="
      line:   "hostname='{{ hostname }}"
    when: sysinit == "openrc"

  # if the network has a DNS server but not a DHCP server
  - name: lineinfile > set local domain name
    lineinfile:
      path:   /etc/conf.d/net
      create: yes
      regexp: "^dns_domain_lo="
      line:   "dns_domain_lo='home-network'"
              # nis_domain_lo="my-nisdomain"    # If a NIS domain is needed
    when: sysinit == "openrc"

  become_user: root
  tags: dns
